
# Official docker compose image.
image:
  name: docker/compose:latest
variables:
  DOCKER_DRIVER: overlay
services:
  - docker:dind

image: docker:latest
image: maven:3.8.4-openjdk-17

before_script:
- docker info
- apk update
- apk upgrade
- apk add python python-dev py-pip build-base
- pip install docker-compose


stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - mvn clean install
    - echo "Compile complete."
    
unit-test-job:
  stage: test
  script:
    - mvn verify
    
postman_tests:
    stage: test
    image: 
        name: postman/newman:alpine
        entrypoint: [""]
    script:
        - docker-compose up --detach
        - sleep 60
        - newman --version
        - newman run postman/SSVE.postman_collection.json

deploy-job:
  stage: deploy
  script:
    - echo "TODO"
