# Configuration pour la BD Postgres
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ADVE
    password: ADVE
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    ddl-auto: create